ServerEvents.recipes(event => {
    event.remove({output: 'create_sa:small_fueling_tank'})
    event.remove({output: 'create_sa:medium_fueling_tank'})
    event.remove({output: 'create_sa:large_fueling_tank'})
    event.remove({output: 'create_sa:brass_jetpack_chestplate'})
    event.remove({output: 'create_sa:copper_jetpack_chestplate'})
    event.remove({output: 'create_sa:andesite_jetpack_chestplate'})
    event.remove({output: 'create_sa:steam_engine'})
    event.remove({output: 'create_sa:heat_engine'})
    event.remove({output: 'create_sa:hydraulic_engine'})
    event.remove({output: 'create_sa:small_filling_tank'})
    event.remove({output: 'create_sa:medium_filling_tank'})
    event.remove({output: 'create_sa:large_filling_tank'})
    event.remove({output: 'create_sa:brass_drill_head'})
    event.remove({output: 'create_sa:flamethrower'})
    event.remove({output: 'create_sa:block_picker'})
    event.remove({output: 'create_sa:grapplin_whisk'})
    event.remove({output: 'create_sa:portable_drill'})
    event.remove({output: 'create_sa:slime_helmet'})
    event.remove({output: 'create_sa:slime_boots'})
})